-- Database Schema for RAG System Chat History
-- Run this SQL in your Supabase SQL Editor

-- Create chat_history table
CREATE TABLE IF NOT EXISTS chat_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  user_message TEXT NOT NULL,
  ai_message TEXT NOT NULL,
  context_used TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_chat_history_user_id ON chat_history(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_history_created_at ON chat_history(created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;

-- Create policy for users to only see their own chat history
CREATE POLICY "Users can view own chat history" ON chat_history
  FOR SELECT
  USING (auth.uid() = user_id);

-- Create policy for users to insert their own chat history
CREATE POLICY "Users can insert own chat history" ON chat_history
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Create policy for users to delete their own chat history
CREATE POLICY "Users can delete own chat history" ON chat_history
  FOR DELETE
  USING (auth.uid() = user_id);

-- Note: Admin can see all chat history
CREATE POLICY "Admins can view all chat history" ON chat_history
  FOR SELECT
  USING (
    auth.uid() IN (
      SELECT id FROM auth.users WHERE email IN (
        'admin@ragdemo.com',
        'sinaubersama89@gmail.com',
        'sopoh006@gmail.com'
      )
    )
  );
